alias ls="ls --color=auto"
alias grep="grep --colour=auto"
alias egrep="egrep --colour=auto"
alias grep="grep --colour=auto"
alias egrep="egrep --colour=auto"
alias fgrep="fgrep --colour=auto"
alias cp="cp -i"            # confirm before overwriting something
alias df="df -h"            # human-readable sizes
alias free="free -m"        # show sizes in MB
alias np="nano -w PKGBUILD"
alias more="less"
alias ll="ls -l"
alias la="ls -A"
alias lal="ls -Al"
alias lla="ls -Al"
alias l="ls -CF"
alias kitten="kitty +kitten"
alias less="less -x4"
{#@@ zoo-work specific aliases @@#}
{%@@ if profile == "zoo-work" @@%}
{{@@ work_vpn @@}}
{%@@ endif @@%}
