# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  fileSystems."/" =
    {
      device = "/dev/mapper/luks-ee979b1e-6385-43d0-af8a-02eed0728e31";
      fsType = "ext4";
    };

  boot.initrd.luks.devices = {
    "luks-ee979b1e-6385-43d0-af8a-02eed0728e31".device = "/dev/disk/by-uuid/ee979b1e-6385-43d0-af8a-02eed0728e31";
    "luks-66137857-a143-43d9-9b29-be2402b867ae".device = "/dev/disk/by-uuid/66137857-a143-43d9-9b29-be2402b867ae";
  };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/27DA-F9D8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [{ device = "/dev/mapper/luks-66137857-a143-43d9-9b29-be2402b867ae"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
