actions:
  pre:
    install-atom-packages: "{{@@ _dotdrop_dotpath @@}}/atom-packages.sh install {{@@ _dotdrop_dotpath @@}}"
  post:
    enable-ssh-agent-service: systemctl --user --now enable ssh-agent.service
config:
  backup: true
  create: true
  dotpath: dotfiles
  link_dotfile_default: link
dotfiles:
  d_vim:
    src: vim
    dst: ~/.vim
    link: link_children
  f_nvidia-settings-rc:
    src: nvidia-settings-rc
    dst: ~/.nvidia-settings-rc
  f_xclients:
    src: Xclients
    dst: ~/.Xclients
  f_bash_logout:
    src: bash_logout
    dst: ~/.bash_logout
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_dir_colors:
    src: dir_colors
    dst: ~/.dir_colors
  f_dmenurc:
    src: dmenurc
    dst: ~/.dmenurc
  f_dmrc:
    src: dmrc
    dst: ~/.dmrc
  d_i3:
    src: i3
    dst: ~/.i3
    link: link_children
  f_pam_environment:
    src: pam_environment
    dst: ~/.pam_environment
  f_profile:
    src: profile
    dst: ~/.profile
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_nord-xresources:
    src: nord-xresources/src/nord
    dst: ~/.Xresources.d/nord
  d_ssh:
    src: ssh
    dst: ~/.ssh
    link: link_children
  d_atom:
    src: atom
    dst: ~/.atom
    link: link_children
    actions:
    - install-atom-packages
  f_bash_aliases:
    src: bash_aliases
    dst: ~/.bash_aliases
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
  f_i3-scrot.conf:
    src: config/i3-scrot.conf
    dst: ~/.config/i3-scrot.conf
  d_i3status:
    src: config/i3status
    dst: ~/.config/i3status
    link: link_children
  f_ssh-agent.service:
    src: config/systemd/user/ssh-agent.service
    dst: ~/.config/systemd/user/ssh-agent.service
    link: nolink
    actions:
    - enable-ssh-agent-service
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
    link: link_children
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
profiles:
  sater-manjaro:
    dotfiles:
    - d_vim
    - f_nvidia-settings-rc
    - f_xclients
    - f_bash_logout
    - f_bash_profile
    - f_bashrc
    - f_dir_colors
    - f_dmenurc
    - f_dmrc
    - d_i3
    - f_pam_environment
    - f_profile
    - f_xinitrc
    - f_xresources
    - f_nord-xresources
    - d_ssh
    - f_bash_aliases
    - f_mimeapps.list
    - f_i3-scrot.conf
    - d_i3status
    - d_ranger
    - f_ssh-agent.service
    - f_gitconfig
    - d_atom
