config:
  backup: true
  create: true
  dotpath: system
dotfiles:
  f_set-monitor-sink:
    src: set-monitor-sink
    dst: /usr/bin/set-monitor-sink
    link: link
  f_fstab:
    src: etc/fstab
    dst: /etc/fstab
  f_local.conf:
    src: etc/fonts/local.conf
    dst: /etc/fonts/local.conf
  d_tmpfiles.d:
    src: etc/tmpfiles.d
    dst: /etc/tmpfiles.d
  f_00-local-userns.conf:
    src: etc/sysctl.d/00-local-userns.conf
    dst: /etc/sysctl.d/00-local-userns.conf
  f_locale.conf:
    src: etc/locale.conf
    dst: /etc/locale.conf
profiles:
  sater-manjaro:
    dotfiles:
    - f_set-monitor-sink
    - f_fstab
    - f_local.conf
    - d_tmpfiles.d
    - f_00-local-userns.conf
    - f_locale.conf
  basic:
    dotfiles:
      - f_local.conf
      - d_tmpfiles.d
      - f_00-local-userns.conf
      - f_locale.conf
