config:
  create: true
  showdiff: true
  dotpath: system
dotfiles:
  f_set-monitor-sink:
    src: set-monitor-sink
    dst: /usr/bin/set-monitor-sink
    link: link
  f_fstab:
    src: etc/fstab
    dst: /etc/fstab
  f_local.conf:
    src: etc/fonts/local.conf
    dst: /etc/fonts/local.conf
  d_tmpfiles.d:
    src: etc/tmpfiles.d
    dst: /etc/tmpfiles.d
  f_00-local-userns.conf:
    src: etc/sysctl.d/00-local-userns.conf
    dst: /etc/sysctl.d/00-local-userns.conf
  f_locale.conf:
    src: etc/locale.conf
    dst: /etc/locale.conf
  f_lightdm:
    src: etc/lightdm/lightdm.conf.d/50-my-custom-config.conf
    dst: /etc/lightdm/lightdm.conf.d/50-my-custom-config.conf
  f_keyboard:
    src: etc/default/keyboard
    dst: /etc/default/keyboard
  f_vconsole:
    src: etc/vconsole.conf
    dst: /etc/vconsole.conf
  f_pulse_conf_script:
    src: etc/pulse/default.pa
    dst: /etc/pulse/default.pa
  f_xsecurelock_environment:
    src: etc/profile.d/xsecurelock.sh
    dst: /etc/profile.d/xsecurelock.sh
  f_docker_config:
    src: docker/config.json
    dst: /root/.docker/config.json
profiles:
  basic-manjaro:
    dotfiles:
    - f_local.conf
    - d_tmpfiles.d
    - f_00-local-userns.conf
    - f_locale.conf
    - f_lightdm
    - f_keyboard
    - f_vconsole
    - f_pulse_conf_script
    - f_xsecurelock_environment
    - f_docker_config
  sater-manjaro:
    dotfiles:
    - f_set-monitor-sink
    - f_fstab
    include:
    - basic-manjaro
  zoo-work:
    include:
    - basic-manjaro
