# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.loader = {
    systemd-boot.enable = false;

    efi = {
      canTouchEfiVariables = true;
      efiSysMountPoint = "/boot";
    };

    grub = {
      enable = true;

      devices = [ "nodev" ];
      default = 1;
      efiSupport = true;
      extraEntries = ''
        menuentry "Windows" {
          insmod part_gpt
          insmod fat
          insmod search_fs_uuid
          insmod chain
          search --fs-uuid --set=root E499-BF2C
          chainloader /EFI/Microsoft/Boot/bootmgfw.efi
        }
      '';
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/eaa55638-e4ce-4cb9-91f4-f78d8352b3f6";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4E7B-7107";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/9314d9f7-9110-496d-8630-efc160124f4b"; } ];

  fileSystems."/mnt/870data" = {
    device = "/dev/disk/by-uuid/01DAF6502F4C7F50";
    fsType = "ntfs";
    options = [
      "nofail"
      "defaults"
      "rw"
      "exec"
      "umask=000"
    ];
  };

  fileSystems."/mnt/980pro1tb" = {
    device = "/dev/disk/by-uuid/01D95E8AEB9E53E0";
    fsType = "ntfs";
    options = [
      "nofail"
      "defaults"
      "rw"
      "exec"
      "umask=000"
    ];
  };

  fileSystems."/mnt/3tb" = {
    device = "/dev/disk/by-uuid/3A54F99154F94FDD";
    fsType = "ntfs";
    options = [
      "nofail"
      "defaults"
      "rw"
      "exec"
      "umask=000"
    ];
  };

  fileSystems."/mnt/4tb" = {
    device = "/dev/disk/by-uuid/7C2BB0666B33046E";
    fsType = "ntfs";
    options = [
      "nofail"
      "defaults"
      "rw"
      "exec"
      "umask=000"
    ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp12s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp13s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    powerManagement.finegrained = false;
    open = false;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.production;
  };

  services.xserver.serverFlagsSection = ''
    Option "BlankTime" "0"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime" "0"
  '';
  services.xserver.screenSection = ''
    Option "metamodes" "DP-2: 5120x1440_240 +0+0; DP-2: nvidia-auto-select +0+0"
  '';
  services.xserver.xrandrHeads = [
    {
      output = "DP-2";
      primary = true;
      monitorConfig = ''
        ModelName "Samsung LC49G95T"
        HorizSync 357.0 - 357.0
        VertRefresh 60.0 - 240.0
        # 5120x1440 239.90 Hz (CVT) hsync: 398.96 kHz; pclk: 2885.25 MHz
        Modeline "5120x1440_240.00"  2885.25  5120 5600 6176 7232  1440 1443 1453 1663 -hsync +vsync
        Option "PreferredMode" "5120x1440_240.00"
        Option "DPMS"
      '';
    }
    {
      output = "HDMI-0";
      monitorConfig = ''
        Option "Enable" "false"
      '';
    }
  ];
}
