# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/325455f2-2ed8-4f00-8e86-00caea50ef6c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/74A0-69FC";
      fsType = "vfat";
    };

  fileSystems."/mnt/3tb" =
    { device = "/dev/disk/by-uuid/3A54F99154F94FDD";
      fsType = "ntfs";
      options = [ "nofail" "defaults" "rw" "exec" "umask=000" ];
    };

  fileSystems."/mnt/4tb" =
    { device = "/dev/disk/by-uuid/cb1e9d0a-240a-427f-a151-a2b65af01663";
      fsType = "ext4";
      options = [ "nofail" "defaults" "rw" "exec" ];
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
