# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  fileSystems."/" =
    {
      device = "/dev/mapper/luks-3b03c428-3390-48c1-80b0-0fa88faf65c9";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-3b03c428-3390-48c1-80b0-0fa88faf65c9".device = "/dev/disk/by-uuid/3b03c428-3390-48c1-80b0-0fa88faf65c9";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/2E04-A765";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [{ device = "/dev/disk/by-uuid/271baeb1-1182-48d9-b00e-1ccc2edf19fa"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
